#!/usr/bin/env sh
# Install Navi language into `/usr/local/navi/`.
# And then link `navi`, `navi-lsp-server` to `/usr/local/bin/`.
set -u
type curl > /dev/null || { echo "curl: not found"; exit 1; }

repo='navi-language/navi'

# request github api, and check if the response is ok
fetch_github_api() {
  url="$1"
  curl --silent --fail "$url" || { echo "Failed to fetch $url"; exit 1; }
}

get_latest_release() {
  fetch_github_api "https://api.github.com/repos/$repo/releases/latest" | # Get latest release from GitHub api
    grep '"tag_name":' |                                               # Get tag line
    sed -E 's/.*"([^"]+)".*/\1/'                                       # Pluck JSON value
}

get_last_nightly_release() {
  fetch_github_api "https://api.github.com/repos/$repo/releases" | # Get latest release from GitHub api
    grep '"tag_name":' |                                               # Get tag line
    sed -E 's/.*"([^"]+)".*/\1/' |                                       # Pluck JSON value
    grep "nightly" | head -n 1
}

app_name='Navi'
bin_name='navi'
tmpdir=.tmp_install

# if args has version override it and not eq "latest"
if test $# -eq 1; then
  if test "$1" = "nightly"; then
    # curl -sSL https://navi-lang.org/install | sh -s -- nightly
    version=$(get_last_nightly_release)
  elif test "$1" != "latest"; then
    # curl -sSL https://navi-lang.org/install | sh -s -- v0.9.0-nightly
    version="$1"
  fi
else
  # curl -sSL https://navi-lang.org/install | sh
  version=$(get_latest_release)
fi

# if version is empty, exit
if test -z "$version"; then
  echo "Fetch version failed, please check your network."
  exit 1
fi

platform="$(uname | tr "[A-Z]" "[a-z]")"  # Linux => linux
arch="$(uname -m | sed 's/x86_64/amd64/')"  # x86_64 => amd64

if [ "$platform" = "darwin" ]; then
	platform="darwin"
  arch="amd64"
fi

echo "Downloading $bin_name@$version ..."

libc=''
# if ldd --version 2>&1 | grep -q 'musl'; then
#   libc='-musl'
# fi

download_url=https://github.com/$repo/releases/download/$version/$bin_name-$platform$libc-$arch.tar.gz
echo $download_url

mkdir -p $tmpdir && cd $tmpdir
if curl --fail -Lo $bin_name.tar.gz $download_url; then
  echo "Download successfully."
else
  echo "Download failed, please check your network."
  exit 1
fi

mkdir -p navi/
tar zxf $bin_name.tar.gz --directory navi/ && rm $bin_name.tar.gz

if test $(id -u) -eq 0; then
  cp -Rf navi /usr/local/

  test -f /usr/local/navi/navi && ln -sf /usr/local/navi/navi /usr/local/bin/
  test -f /usr/local/navi/navi-lsp-server && ln -sf /usr/local/navi/navi-lsp-server /usr/local/bin/
else
  sudo cp -Rf navi /usr/local/

  sudo test -f /usr/local/navi/navi && sudo ln -sf /usr/local/navi/navi /usr/local/bin/
  sudo test -f /usr/local/navi/navi-lsp-server && sudo ln -sf /usr/local/navi/navi-lsp-server /usr/local/bin/
fi

cd ..
rm -Rf $tmpdir

echo "$app_name $version has installed successfully."
echo ""
echo "You can use `$bin_name -h` to get help."
echo ""